version: "3.6"
services:
  meliproxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080"
    depends_on: 
      - redis
    environment:
      PROXY_PORT: :8080
      IP_RATE_LIMIT: 10
      IP_PATH_RATE_LIMIT: 10
      IP_PATH_RATE_LIMIT_PER_SECOND: 60
      PATH_RATE_LIMIT: 10
      PATH_RATE_LIMIT_PER_SECOND: 60
      LOCK_RETRY: 100
      API_MERCADO_LIBRE: https://api.mercadolibre.com
      REDIS_URL: redis:6379    
      
  redis:
    image: "redis:alpine"
    restart: unless-stopped

  nginx:
    build: "./nginx"
    ports:
      - "4000:4000"
    depends_on:
      - "meliproxy"